from typing import Protocol

from domain.ingestion.entities import Chunk, Document, Source


class SourceRepository(Protocol):
    def add(self, source: Source) -> None: ...
    def get_by_id(self, source_id: str) -> Source | None: ...
    def update(self, source: Source) -> None: ...


class DocumentRepository(Protocol):
    def add(self, document: Document) -> None: ...
    def get_by_source_id(self, source_id: str) -> Document | None: ...
    def update(self, document: Document) -> None: ...


class ChunkRepository(Protocol):
    def add_many(self, chunks: list[Chunk]) -> None: ...
    def list_by_source_id(self, source_id: str) -> list[Chunk]: ...
    def update_embeddings(self, chunks: list[Chunk]) -> None: ...


class SourceLoader(Protocol):
    async def load(self, source: Source, file_bytes: bytes) -> str: ...


class EmbeddingProvider(Protocol):
    dimension: int

    def embed(self, texts: list[str]) -> list[list[float]]: ...


class SearchIndexer(Protocol):
    def index_chunks(self, chunks: list[Chunk], source_type: str) -> None: ...


class Storage(Protocol):
    def upload(self, key: str, data: bytes) -> None: ...
    def download(self, key: str) -> bytes: ...


class AsyncSourceRepository(Protocol):
    async def add(self, source: Source) -> None: ...
    async def get_by_id(self, source_id: str) -> Source | None: ...
    async def list_by_workspace_id(self, workspace_id: str) -> list[Source]: ...


class AsyncChunkRepository(Protocol):
    async def get_by_ids(self, chunk_ids: list[str]) -> list[Chunk]: ...
