from typing import Protocol

from domain.workspaces.entities import Workspace


class WorkspaceRepository(Protocol):
    async def add(self, workspace: Workspace) -> None: ...
    async def get_by_id(self, workspace_id: str) -> Workspace | None: ...
    async def save(self, workspace: Workspace) -> None: ...
    async def delete(self, workspace: Workspace) -> None: ...
