apiVersion: v1
kind: Secret
metadata:
  name: kip-secrets
  namespace: kip
stringData:
  POSTGRES_USER: kip
  POSTGRES_PASSWORD: kip
  RABBITMQ_DEFAULT_USER: kip
  RABBITMQ_DEFAULT_PASS: kip
  S3_ACCESS_KEY: kip
  S3_SECRET_KEY: kipkipkip
  JWT_SECRET: local-dev-secret
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  SENTRY_DSN: ""
