import datetime
from typing import Protocol

from domain.auth.entities import EmailVerificationToken, RefreshToken, User


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: str) -> User | None: ...
    async def update(self, user: User) -> None: ...


class EmailVerificationTokenRepository(Protocol):
    async def add(self, token: EmailVerificationToken) -> None: ...
    async def get_by_hash(self, token_hash: str) -> EmailVerificationToken | None: ...
    async def update(self, token: EmailVerificationToken) -> None: ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> None: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def update(self, token: RefreshToken) -> None: ...
    async def revoke_all_for_user(self, user_id: str, now: datetime.datetime) -> None: ...


class EmailSender(Protocol):
    async def send_verification_email(self, to: str, token: str) -> None: ...
